import '../assets/styles/index.css'

import localFont from 'next/font/local'

const font = localFont({
  src: '../assets/fonts/xiaolai.ttf',
  variable: '--font-xiaolai',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${font.variable}`}>
      <body>
        {children}
        <div className="bg-[url('/kirakirashiro23.png')] fixed inset-0 -z-10 opacity-25 bg-cover bg-center" />
      </body>
    </html>
  )
}
